const isAdminEntry=document.body.dataset.startMode==='portal';
const configuredApiBase=new URLSearchParams(location.search).get('api')?.replace(/\/$/,'')||'';
const state={mode:isAdminEntry?'portal':'mobile',mobileScreen:'home',portalScreen:'dashboard',selectedTime:'10:30',actionsView:'list',mapSelected:'Dom omladine',notificationsRead:false,operationsQuery:'',operationsStatus:'all',eventQuery:'',eventMunicipality:'all',eventStatus:'all',selectedPortalDay:'19',api:{status:configuredApiBase?'ready':'not-configured',message:configuredApiBase?'Adresa je podešena. Pokrenite proveru veze.':'API adresa nije podešena',checkedAt:null}};

const mobileCatalog=[
  {title:'Glavni tok',items:[['home','Početni ekran'],['actions','Akcije i mapa'],['action-detail','Detalj akcije'],['booking','Izbor termina'],['booking-success','Potvrđen termin'],['appointments','Moji termini']]},
  {title:'Lični podaci',items:[['profile','Profil'],['card','Digitalna kartica'],['history','Istorija davanja'],['donation-detail','Detalj davanja'],['corrections','Zahtev za ispravku'],['achievements','Kapljice i jubileji']]},
  {title:'Informacije i podrška',items:[['notifications','Centar obaveštenja'],['education','Vesti i edukacija'],['faq','Česta pitanja i pomoć'],['support','Podrška posle davanja']]},
  {title:'Podešavanja i buduće usluge',items:[['privacy','Privatnost i komunikacija'],['pause','Privremena pauza poziva'],['questionnaire','Digitalni upitnik - buduća faza']]}
];

const screenDecisions={
  welcome:[['Javni pristup','Vesti, akcije i edukacija dostupni su bez naloga.'],['Ton','Topao i miran, bez pritiska na korisnika.'],['Pristupačnost','Ćirilica, latinica i veći tekst od prvog dana.']],
  registration:[['Minimalni podaci','Tražimo samo podatke potrebne za nalog.'],['Vrsta korisnika','Postojeći davalac, prvi put ili podržavalac.'],['Saglasnosti','Odvojene od samog otvaranja naloga.']],
  verification:[['Kanal','Kod putem SMS-a ili imejla.'],['Bezbednost','Ograničen broj pokušaja i vremenski rok.'],['Podrška','Jasan alternativni kontakt.']],
  'link-record':[['Identitet','Spajanje sa evidencijom zahteva dodatnu proveru.'],['Duple evidencije','Ne spajaju se automatski.'],['Ograničenje','Bez potvrde nema zvanične istorije ni krvne grupe.']],
  home:[['Status','Prikazuje vremenski razmak, ne medicinsku podobnost.'],['Prioritet','Sledeća akcija i termin su najvidljiviji.'],['Podatak','Svaki važan podatak ima izvor i datum ažuriranja.']],
  actions:[['Lista i mapa','Oba prikaza dele iste filtere.'],['Privatnost lokacije','Mapa radi i bez praćenja trenutne lokacije.'],['Dostupnost','Broj termina se prikazuje samo ako je ažuran.']],
  'action-detail':[['Vrsta pristupa','Javna ili zatvorena akcija je jasno označena.'],['Priprema','Kratko i stručno odobreno uputstvo.'],['Kontakt','Odgovorna osoba i navigacija bez skrivenih radnji.']],
  booking:[['Provera','Evidencija se ponovo proverava pre rezervacije.'],['Kapacitet','Samo stvarno slobodni termini.'],['Izbor','Korisnik može doći bez rezervacije gde je dozvoljeno.']],
  'booking-success':[['Potvrda','Termin dobija jedinstvenu potvrdu.'],['Podsetnici','Korisnik bira vreme obaveštenja.'],['Izmena','Pomeranje i otkazivanje su dostupni bez kaznenog tona.']],
  appointments:[['Aktivni termini','Jasno odvojeni od prethodnih poseta.'],['Otkazivanje','Odmah oslobađa kapacitet.'],['Lista čekanja','Ponuda mesta ima vremensko ograničenje.']],
  profile:[['Potvrđeni podaci','Vizuelno odvojeni od korisničkog unosa.'],['Kontrola','Privatnost, komunikacija i gašenje naloga.'],['Evidencija','Gašenje naloga ne briše obaveznu dokumentaciju.']],
  card:[['QR bez zdravstvenih podataka','Kod služi samo za identifikaciju.'],['Rok važenja','Kod je vremenski ograničen.'],['Alternativa','Dokument ustanove i dalje može biti obavezan.']],
  history:[['Obuhvat','Jasno piše koji period pokriva evidencija.'],['Vrste davanja','Puna krv i komponente su odvojene.'],['Ispravke','Svaki sporni zapis vodi ka zahtevu za proveru.']],
  'donation-detail':[['Minimum podataka','Bez nepotrebnih medicinskih detalja.'],['Potvrda','Motivaciona zahvalnica nije zvaničan dokument.'],['Izvor','Uvek je vidljivo ko je potvrdio zapis.']],
  corrections:[['Trag izmene','Zahtev, odgovor i promena ostaju zabeleženi.'],['Dokaz','Prilog je opcion i zaštićen.'],['Rok','Korisnik dobija očekivano vreme odgovora.']],
  achievements:[['Bez rangiranja','Nema pritiska ni poređenja među davaocima.'],['Potvrđena davanja','Kapljice dolaze samo iz zvanične evidencije.'],['Deljenje','Uvek ga pokreće sam korisnik.']],
  notifications:[['Neutralan zaključani ekran','Bez krvne grupe i zdravstvenih razloga.'],['Ograničenje učestalosti','Kampanje se ne preklapaju.'],['Aktuelnost','Stara poruka vodi do važećeg statusa.']],
  education:[['Odobren sadržaj','Svaki tekst ima izvor i datum provere.'],['Javni pristup','Sadržaj je dostupan bez naloga.'],['Pristupačnost','Titlovi i čitljiv format.']],
  faq:[['Granice automatizacije','Pomoćnik ne procenjuje podobnost.'],['Izvor odgovora','Prikazuje odobren izvor i datum.'],['Čovek u toku','Uvek postoji kontakt sa Zavodom.']],
  support:[['Nije hitna služba','Ograničenje kanala je jasno.'],['Posle davanja','Samo stručni, odobreni saveti.'],['Privatnost','Osetljive informacije idu ovlašćenoj službi.']],
  privacy:[['Odvojeni izbori','Pozivi, vesti, lokacija i deljenje nisu jedna saglasnost.'],['Promenljivo','Korisnik menja odluku u svakom trenutku.'],['Osnovna usluga','Isključena lokacija ne blokira aplikaciju.']],
  pause:[['Bez objašnjenja','Razlog pauze nije obavezan.'],['Jasan datum','Korisnik vidi kada se pozivi nastavljaju.'],['Važi svuda','Sve kampanje poštuju pauzu.']],
  questionnaire:[['Buduća faza','Prvo se odobravaju obrazac i postupak.'],['QR zaštita','Kod ne sadrži odgovore.'],['Pregled ostaje','Upitnik ne zamenjuje razgovor i odluku lekara.']]
};

const $=selector=>document.querySelector(selector);
const $$=selector=>[...document.querySelectorAll(selector)];
const mobileScreen=$('#mobile-screen');
const portalScreen=$('#portal-screen');
const dialog=$('#prototype-dialog');
let toastTimer;
let streetMap;
const mapLocations={
  'Dom omladine':{coords:[44.8166,20.4617],info:'Beograd · 8 slobodnih termina'},
  'Studentski kulturni centar':{coords:[44.8105,20.4663],info:'Beograd · 12 slobodnih termina'},
  'Crveni krst Zemun':{coords:[44.8463,20.4097],info:'Zemun · dolazak bez rezervacije'}
};

function showToast(message){const toast=$('#toast');toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2600)}
function pill(label,type='neutral'){return `<span class="pill ${type}">${label}</span>`}
function statusTone(status){return ({Zakazan:'warning',Prijavljen:'info','Kod tima':'success','Nije došao':'neutral'})[status]||'neutral'}
function apiStatusMarkup(){const stateClass=state.api.status==='connected'?'success':state.api.status==='failed'?'warning':'neutral';const label=state.api.status==='connected'?'API povezan':state.api.status==='checking'?'Provera API-ja':state.api.status==='failed'?'Veza nije dostupna':state.api.status==='ready'?'Spremno za proveru':'API nije podešen';return `<div class="api-status"><span class="api-status-dot ${stateClass}"></span><div><strong>${label}</strong><small>${state.api.message}</small></div>${state.api.checkedAt?`<time>${state.api.checkedAt}</time>`:''}</div>`}
async function checkConfiguredApi(resource='/health'){
  if(!configuredApiBase){state.api={status:'not-configured',message:'Dodajte ?api=https://api-vasa-domena da portal čita odobreni API.',checkedAt:null};renderPortal('integrations');return}
  state.api={status:'checking',message:'Proveravamo vezu i odgovor servera…',checkedAt:null};renderPortal('integrations');
  const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),5000);
  try{const response=await fetch(`${configuredApiBase}${resource}`,{headers:{'X-Demo-Role':'admin'},signal:controller.signal});const body=await response.json();if(!response.ok)throw new Error(body?.error?.message||`HTTP ${response.status}`);state.api={status:'connected',message:resource==='/health'?'Demonstracioni API odgovara i spreman je za ugovorene rute.':'Portal ruta je odgovorila bez zdravstvenih podataka.',checkedAt:new Intl.DateTimeFormat('sr-Latn',{hour:'2-digit',minute:'2-digit'}).format(new Date())};showToast('API veza je proverena.')}catch(error){const message=error instanceof Error&&error.name==='AbortError'?'Veza je istekla — proverite javnu HTTPS API adresu i CORS pravilo.':error instanceof Error?error.message:'API nije dostupan.';state.api={status:'failed',message,checkedAt:new Intl.DateTimeFormat('sr-Latn',{hour:'2-digit',minute:'2-digit'}).format(new Date())};showToast('API nije dostupan — portal ostaje u demo režimu.')}finally{clearTimeout(timeout)}renderPortal('integrations')
}
function icon(name){const paths={bell:'<path d="M18 9a6 6 0 0 0-12 0c0 7-3 7-3 8h18c0-1-3-1-3-8Z"/><path d="M10 21h4"/>',arrow:'<path d="m9 18 6-6-6-6"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m16.5 16.5 4 4"/>',settings:'<path d="M4 6h10M18 6h2M4 12h3M11 12h9M4 18h8M16 18h4"/><circle cx="16" cy="6" r="2"/><circle cx="9" cy="12" r="2"/><circle cx="14" cy="18" r="2"/>',card:'<rect x="3" y="5" width="18" height="14" rx="3"/><path d="M3 10h18M7 15h4"/>',heart:'<path d="M20.8 4.7a5.5 5.5 0 0 0-7.8 0L12 5.8l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.5a5.5 5.5 0 0 0 0-7.8Z"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9.8 9a2.4 2.4 0 1 1 3.5 2.1c-1 .5-1.3 1-1.3 2M12 17h.01"/>'};return `<svg class="ui-icon" viewBox="0 0 24 24" aria-hidden="true">${paths[name]||paths.heart}</svg>`}
function mobileHeader(title,back='home',action=''){return `<header class="mobile-page-header"><button class="back-button" data-mobile-screen="${back}" aria-label="Nazad">${icon('arrow')}</button><h2>${title}</h2>${action||'<span style="width:40px"></span>'}</header>`}
function eventCard(name,city,date='12',day='SUB',time='10:00-14:00',screen='action-detail'){return `<button class="event-card" data-mobile-screen="${screen}"><span class="date-tile"><span>${day}</span><strong>${date}</strong><span>OKT</span></span><span class="event-info"><strong>${name}</strong><span>${city}</span><span>${time}</span></span><span class="chevron">›</span></button>`}
function qrCode(){const size=21;const inFinder=(row,col)=>[[0,0],[0,14],[14,0]].some(([top,left])=>row>=top&&row<top+7&&col>=left&&col<left+7);const finder=(row,col)=>{const local=[row%7,col%7];return local[0]===0||local[0]===6||local[1]===0||local[1]===6||(local[0]>=2&&local[0]<=4&&local[1]>=2&&local[1]<=4)};return `<div class="qr-code" role="img" aria-label="Jednokratni QR kod za identifikaciju">${Array.from({length:size*size},(_,index)=>{const row=Math.floor(index/size),col=index%size;const filled=inFinder(row,col)?finder(row,col):((row*11+col*7+row*col)%9<4);return `<i class="${filled?'filled':''}"></i>`}).join('')}</div>`}
function renderStreetMap(){const container=$('#action-street-map');if(!container||!window.L)return;streetMap=L.map(container,{zoomControl:false,attributionControl:true}).setView([44.822,20.445],12);L.control.zoom({position:'bottomright'}).addTo(streetMap);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(streetMap);Object.entries(mapLocations).forEach(([name,location])=>{const selected=name===state.mapSelected;const marker=L.circleMarker(location.coords,{radius:selected?10:8,color:'#fff',weight:3,fillColor:selected?'#ff8068':'#b51f45',fillOpacity:1}).addTo(streetMap);marker.bindPopup(`<strong>${name}</strong><br><span>${location.info}</span>`);marker.on('click',()=>{state.mapSelected=name;renderMobile('actions')})});streetMap.invalidateSize()}

function renderMobileList(){
  $('#mobile-screen-list').innerHTML=mobileCatalog.map(group=>`<section class="screen-group"><h3>${group.title}</h3>${group.items.map(([id,label])=>`<button data-mobile-screen="${id}">${label}</button>`).join('')}</section>`).join('');
}

function renderChecklist(){
  const items=screenDecisions[state.mobileScreen]||screenDecisions.home;
  $('#decision-checklist').innerHTML=items.map((item,index)=>`<div class="check-item"><span>${index+1}</span><div><strong>${item[0]}</strong><small>${item[1]}</small></div></div>`).join('');
}

function renderMobile(screen=state.mobileScreen){
  state.mobileScreen=screen;
  const labels=Object.fromEntries(mobileCatalog.flatMap(group=>group.items));
  $('#mobile-flow-label').textContent=labels[screen]||screen;
  $$('#mobile-screen-list [data-mobile-screen]').forEach(button=>button.classList.toggle('active',button.dataset.mobileScreen===screen));
  const root={actions:'actions','action-detail':'actions',booking:'actions','booking-success':'actions',appointments:'actions',notifications:'notifications',profile:'profile',card:'profile',history:'profile','donation-detail':'profile',corrections:'profile',achievements:'profile',privacy:'profile',pause:'profile',questionnaire:'profile'}[screen]||'home';
  const onboarding=['welcome','registration','verification','link-record'].includes(screen);
  $('#mobile-nav').classList.toggle('hidden',onboarding);
  $$('#mobile-nav [data-mobile-screen]').forEach(button=>button.classList.toggle('active',button.dataset.mobileScreen===root));
  mobileScreen.innerHTML=mobileTemplates[screen]?.()||mobileTemplates.home();
  if(screen==='actions'&&state.actionsView==='map')requestAnimationFrame(renderStreetMap);
  mobileScreen.scrollTop=0;
  renderChecklist();
  history.replaceState(null,'',`#mobile/${screen}`);
}

const mobileTemplates={
  welcome:()=>`<section class="onboarding"><div class="drop-hero"><div class="drop-shape"></div></div><span class="eyebrow">DOBRO DOŠLI</span><h1>Davanje krvi počinje dobrom informacijom.</h1><p>Pronađite akciju, zakažite termin i pratite potvrđenu istoriju davanja.</p><div class="pagination-dots"><span class="active"></span><span></span><span></span></div><div class="onboarding-actions"><button class="primary-button full" data-mobile-screen="registration">Otvori nalog</button><button class="ghost-button" data-mobile-screen="home">Nastavi bez naloga</button></div><p class="helper">Bez naloga su dostupne akcije, vesti, mapa i kontakti.</p></section>`,
  registration:()=>`${mobileHeader('Otvaranje naloga','welcome')}<div class="progress-track"><span style="width:33%"></span></div><form class="form-stack" onsubmit="return false"><div class="field"><label>Ime i prezime</label><input value="Milica Petrović"></div><div class="field"><label>Broj mobilnog telefona</label><input value="+381 64 123 4567"></div><div class="field"><label>Datum rođenja</label><input type="date" value="1992-04-16"></div><div class="field"><label>Kako želite da koristite aplikaciju?</label><select><option>Već sam davalac krvi</option><option>Želim prvi put da dam krv</option><option>Želim samo informacije</option></select></div><label class="choice-card selected"><input type="checkbox" checked><div><strong>Prihvatam uslove korišćenja</strong><small>Obaveštenja i lokacija biraju se odvojeno kasnije.</small></div></label><button class="primary-button full" data-mobile-screen="verification">Nastavi</button></form>`,
  verification:()=>`${mobileHeader('Potvrda kontakta','registration')}<div class="progress-track"><span style="width:66%"></span></div><div class="info-box">Kod je poslat na broj koji se završava sa 4567.</div><div class="form-stack" style="margin-top:18px"><div class="field"><label>Unesite šestocifreni kod</label><input inputmode="numeric" value="284 913" style="font-size:1.35rem;letter-spacing:.18em;text-align:center"></div><button class="primary-button full" data-mobile-screen="link-record">Potvrdi broj</button><button class="ghost-button" data-action="resend-code">Pošalji novi kod</button></div>`,
  'link-record':()=>`${mobileHeader('Povezivanje evidencije','verification')}<div class="progress-track"><span style="width:100%"></span></div><div class="warning-box">Povezivanje služi da samo vi vidite svoju potvrđenu istoriju. Podaci se ne spajaju bez provere identiteta.</div><div class="form-stack" style="margin-top:15px"><div class="field"><label>Lični broj davaoca</label><input value="D-104827"></div><div class="field"><label>Poslednje poznato davanje</label><input type="date" value="2024-06-14"></div><button class="primary-button full" data-mobile-screen="home">Pošalji na proveru</button><button class="ghost-button" data-mobile-screen="home">Preskoči za sada</button></div><p class="helper">Dok provera traje, možete koristiti javne funkcije aplikacije.</p>`,
  home:()=>`<div class="mobile-heading"><div><span class="welcome-note">Dobro jutro</span><h2>Zdravo, Milice</h2></div><button class="icon-button notification-button" data-mobile-screen="notifications" aria-label="Obaveštenja">${icon('bell')}<span class="notification-badge"></span></button></div><article class="eligibility-card"><div class="care-kicker"><span class="care-dot"></span>Vaša evidencija je ažurna</div><span class="small-label">OKVIRNI NAREDNI DATUM</span><div class="date-row"><strong>12. oktobar</strong><span class="calendar-icon"><small>OKT</small>12</span></div><p>Ovo je informativni datum. Konačnu procenu uvek obavlja lekar prilikom dolaska.</p><button class="primary-button full" data-mobile-screen="actions">Pronađi akciju ${icon('arrow')}</button></article><div class="stats-grid"><article><span>Poslednje davanje</span><strong>14. jun 2024.</strong><small>Potvrđen zapis</small></article><article><span>Vaš doprinos</span><strong>5 davanja</strong><small>Hvala što pomažete</small></article></div><div class="section-heading"><h3>Sledeća akcija</h3><button data-mobile-screen="actions">Prikaži sve</button></div>${eventCard('Dom omladine','Beograd, Makedonska 22')}<div class="human-help"><span class="human-help-icon">${icon('help')}</span><div><strong>Niste sigurni odakle da počnete?</strong><small>Pročitajte proverene odgovore ili kontaktirajte Zavod.</small></div><button data-mobile-screen="faq" aria-label="Otvori pomoć">${icon('arrow')}</button></div><button class="quick-card" data-mobile-screen="card"><span class="quick-icon">${icon('card')}</span><span><strong>Digitalna kartica</strong><small>Bezbedna identifikacija na prijemu</small></span><span class="chevron">›</span></button>`,
  actions:()=>`${mobileHeader('Akcije','home',`<button class="icon-button" aria-label="Pretraga">${icon('search')}</button>`)}<div class="segmented" role="tablist"><button class="${state.actionsView==='list'?'active':''}" data-action="show-action-list" role="tab">Lista</button><button class="${state.actionsView==='map'?'active':''}" data-action="show-action-map" role="tab">Mapa</button></div><div class="chips"><button class="chip active">Ove nedelje</button><button class="chip">U blizini</button><button class="chip">Slobodni termini</button></div>${state.actionsView==='list'?`<div class="list-caption"><span>${icon('heart')}</span><div><strong>3 akcije za vas</strong><small>Odaberite lokaciju da vidite detalje i termine.</small></div></div>${eventCard('Dom omladine','Beograd · još 8 termina')}${eventCard('Studentski kulturni centar','Novi Sad · još 12 termina','15','UTO','09:00-13:00')}${eventCard('Crveni krst Zemun','Zemun · dolazak bez rezervacije','18','PET','11:00-15:00')}`:`<section class="live-map" aria-label="Interaktivna ulična mapa akcija"><div class="map-toolbar"><span class="map-live-dot"></span><span>Ulična mapa · ažurirano pre 2 min</span><button class="map-locate" data-action="locate-map" aria-label="Prikaži sve lokacije">⌖</button></div><div id="action-street-map" class="street-map" aria-label="OpenStreetMap prikaz akcija"></div><article class="map-selection"><span class="map-selection-dot"></span><div><strong>${state.mapSelected}</strong><small>${mapLocations[state.mapSelected].info}</small></div><button data-mobile-screen="action-detail">Detalji</button></article></section>`}`,
  'action-detail':()=>`${mobileHeader('Detalj akcije','actions')}<article class="detail-hero"><span class="pill success">Javna akcija</span><h3>Dom omladine</h3><p class="helper">Subota, 12. oktobar · 10:00-14:00</p></article><div class="detail-list"><div class="detail-row"><span>⌖</span><div><strong>Makedonska 22, Beograd</strong><small>Otvori navigaciju</small></div></div><div class="detail-row"><span>◷</span><div><strong>8 slobodnih termina</strong><small>Podatak ažuriran danas u 09:32</small></div></div><div class="detail-row"><span>◎</span><div><strong>Organizator: Zavod</strong><small>Kontakt 011 344 00 44</small></div></div></div><div class="info-box">Ponesite dokument sa fotografijom, pojedite lagan obrok i pijte dovoljno tečnosti.</div><button class="primary-button full" style="margin-top:14px" data-mobile-screen="booking">Zakaži termin</button><button class="ghost-button" style="width:100%;margin-top:8px" data-action="follow-event">Prati promene</button>`,
  booking:()=>`${mobileHeader('Izbor termina','action-detail')}<div class="detail-hero"><span class="small-label">DOM OMLADINE</span><h3>Subota, 12. oktobar</h3><p class="helper">Izaberite slobodno vreme dolaska.</p></div><div class="section-heading"><h3>Prepodne</h3></div><div class="time-grid">${['10:00','10:30','11:00','11:30','12:00','12:30'].map((time,index)=>`<button class="time-slot ${time===state.selectedTime?'selected':''}" data-time="${time}" ${index===2?'disabled':''}>${time}</button>`).join('')}</div><div class="choice-card selected"><input type="checkbox" checked><div><strong>Podseti me</strong><small>Dan ranije i dva sata pre termina.</small></div></div><div class="warning-box" style="margin-top:12px">Pre potvrde sistem ponovo proverava raspoloživu evidenciju. Ovo nije medicinsko odobrenje.</div><button class="primary-button full" style="margin-top:14px" data-action="confirm-booking">Potvrdi ${state.selectedTime}</button>`,
  'booking-success':()=>`<section class="success-state"><div class="success-mark">✓</div><h2>Termin je potvrđen</h2><p>Subota, 12. oktobar u ${state.selectedTime}<br>Dom omladine, Beograd</p><div class="digital-card" style="text-align:left;margin-top:20px"><span class="small-label" style="color:#f4d9de">BROJ REZERVACIJE</span><h3 style="font-size:1.6rem;letter-spacing:.12em">DK-284913</h3><p>Prikažite kod na prijemu ako vas zaposleni zatraži.</p></div><div class="onboarding-actions"><button class="primary-button full" data-mobile-screen="appointments">Moji termini</button><button class="ghost-button" data-mobile-screen="home">Nazad na početnu</button></div></section>`,
  appointments:()=>`${mobileHeader('Moji termini','home')}<div class="section-heading"><h3>Predstojeći</h3>${pill('1 aktivan','success')}</div><article class="detail-hero"><span class="small-label">SUBOTA · 12. OKTOBAR</span><h3>Dom omladine · ${state.selectedTime}</h3><p class="helper">Makedonska 22, Beograd</p><div class="button-row"><button class="ghost-button" data-mobile-screen="booking">Promeni</button><button class="danger-button" data-action="cancel-booking">Otkaži</button></div></article><div class="section-heading"><h3>Prethodne posete</h3></div><div class="timeline"><div class="timeline-item"><h3>14. jun 2024.</h3><p>Potvrđeno davanje · Institut za transfuziju</p></div><div class="timeline-item"><h3>2. novembar 2023.</h3><p>Potvrđeno davanje · Dom omladine</p></div></div>`,
  profile:()=>`${mobileHeader('Moj profil','home',`<button class="icon-button" data-mobile-screen="privacy" aria-label="Podešavanja">${icon('settings')}</button>`)}<article class="profile-card"><span class="avatar">MP</span><div><strong>Milica Petrović</strong><small>Potvrđeni davalac</small></div></article><div class="menu-list"><button class="menu-row" data-mobile-screen="card"><span class="menu-icon">▣</span><span><strong>Digitalna kartica</strong><small>Identifikacija na prijemu</small></span><span>›</span></button><button class="menu-row" data-mobile-screen="history"><span class="menu-icon">▥</span><span><strong>Istorija davanja</strong><small>Potvrđeni zapisi i ispravke</small></span><span>›</span></button><button class="menu-row" data-mobile-screen="achievements"><span class="menu-icon">◆</span><span><strong>Kapljice i jubileji</strong><small>Lična priznanja bez rangiranja</small></span><span>›</span></button><button class="menu-row" data-mobile-screen="privacy"><span class="menu-icon">◉</span><span><strong>Privatnost i komunikacija</strong><small>Lokacija, poruke i deljenje</small></span><span>›</span></button><button class="menu-row" data-mobile-screen="pause"><span class="menu-icon">◌</span><span><strong>Pauziraj pozive</strong><small>Privremeno ne primaj pozive</small></span><span>›</span></button></div>`,
  card:()=>`${mobileHeader('Digitalna kartica','profile')}<article class="digital-card"><div class="card-top"><strong>Kartica davaoca</strong><span>◆</span></div><h3>Milica Petrović</h3><p>Davalac D-104827 · identitet potvrđen</p><div class="qr-wrap">${qrCode()}</div><p class="qr-expiry">Jednokratni kod važi još 04:52</p></article><div class="warning-box" style="margin-top:14px">QR kod služi samo za identifikaciju na prijemu. Ne sadrži zdravstvene odgovore i ne zamenjuje dokument koji ustanova zahteva.</div><button class="ghost-button" style="width:100%;margin-top:10px" data-action="refresh-qr">Osveži kod</button>`,
  history:()=>`${mobileHeader('Istorija davanja','profile')}<div class="info-box">Prikaz obuhvata potvrđene zapise dostupne od 2021. godine.</div><div class="stats-grid"><article><span>Potvrđeno ukupno</span><strong>5 davanja</strong></article><article><span>Sledeći jubilej</span><strong>10 davanja</strong></article></div><div class="timeline"><div class="timeline-item"><h3>14. jun 2024.</h3><p>Puna krv · Institut za transfuziju, Beograd</p>${pill('Potvrđeno','success')} <button class="table-button" data-mobile-screen="donation-detail">Detalji</button></div><div class="timeline-item"><h3>2. novembar 2023.</h3><p>Puna krv · Dom omladine, Beograd</p>${pill('Potvrđeno','success')}</div><div class="timeline-item"><h3>18. mart 2023.</h3><p>Puna krv · Crveni krst, Novi Sad</p>${pill('Potvrđeno','success')}</div></div><button class="secondary-button" data-mobile-screen="corrections">Nedostaje davanje ili postoji greška?</button>`,
  'donation-detail':()=>`${mobileHeader('Detalj davanja','history')}<article class="detail-hero"><span class="pill success">Potvrđeno</span><h3>14. jun 2024.</h3><p class="helper">Puna krv</p></article><div class="detail-list"><div class="detail-row"><span>⌖</span><div><strong>Institut za transfuziju</strong><small>Beograd</small></div></div><div class="detail-row"><span>✓</span><div><strong>Evidentirano 14. juna u 13:48</strong><small>Potvrdio ovlašćeni zaposleni</small></div></div><div class="detail-row"><span>▤</span><div><strong>Potvrda o davanju</strong><small>Zvanični dokument ustanove</small></div></div></div><button class="primary-button full" data-action="download-certificate">Preuzmi potvrdu</button><button class="ghost-button" style="width:100%;margin-top:8px" data-mobile-screen="corrections">Prijavi grešku</button>`,
  corrections:()=>`${mobileHeader('Zahtev za ispravku','history')}<div class="info-box">Zaposleni proverava zahtev i odgovara kroz aplikaciju. Sve promene ostaju zabeležene.</div><form class="form-stack" style="margin-top:14px" onsubmit="return false"><div class="field"><label>Vrsta zahteva</label><select><option>Nedostaje potvrđeno davanje</option><option>Netačan datum ili lokacija</option><option>Druga greška</option></select></div><div class="field"><label>Datum davanja</label><input type="date" value="2022-09-08"></div><div class="field"><label>Opis</label><textarea>Davala sam krv u mobilnoj ekipi u Novom Sadu, ali zapis nije prikazan.</textarea></div><div class="choice-card"><input type="checkbox"><div><strong>Imam dokument kao dokaz</strong><small>Prilog će biti dostupan samo ovlašćenom osoblju.</small></div></div><button class="primary-button full" data-action="send-correction">Pošalji zahtev</button></form>`,
  achievements:()=>`${mobileHeader('Kapljice i jubileji','profile')}<section class="achievement-hero"><span class="achievement-count">5</span><div><span class="small-label">POTVRĐENIH DAVANJA</span><h3>Svako davanje ostavlja trag dobrote.</h3><p>Jubileji beleže kontinuitet — bez rangiranja i pritiska.</p></div></section><section class="giving-path" aria-label="Put davanja i jubileja"><div class="path-line"></div><article class="path-item earned"><span class="path-dot">♥</span><div><small>14. jun 2024.</small><strong>5. davanje</strong><p>Jubilej kontinuiteta</p></div></article><article class="path-item"><span class="path-dot">●</span><div><small>2. novembar 2023.</small><strong>4. davanje</strong><p>Potvrđeno u evidenciji</p></div></article><article class="path-item"><span class="path-dot">●</span><div><small>18. mart 2023.</small><strong>3. davanje</strong><p>Potvrđeno u evidenciji</p></div></article><article class="path-item future"><span class="path-dot">10</span><div><small>Sledeći jubilej</small><strong>10 davanja</strong><p>Još 5 potvrđenih davanja</p></div></article></section><div class="section-heading"><h3>Zahvalnice</h3><button data-action="show-thanks">Prikaži sve</button></div><div class="gratitude-grid"><button class="gratitude-card" data-action="show-thanks"><span>♥</span><strong>Hvala što dajete</strong><small>Za 5 potvrđenih davanja</small></button><button class="gratitude-card coral" data-action="show-thanks"><span>✦</span><strong>Kap kontinuiteta</strong><small>Vaša najnovija zahvalnica</small></button></div><button class="secondary-button" data-action="share-achievement">Podeli zahvalnicu</button>`,
  notifications:()=>`${mobileHeader('Obaveštenja','home','<button class="text-button" data-action="mark-read">'+(state.notificationsRead?'Pročitano':'Pročitaj sve')+'</button>')}<button class="notification-item clickable ${state.notificationsRead?'':'unread'}" data-mobile-screen="actions"><span class="notification-icon">⌖</span><span><h3>Nova akcija u vašoj opštini</h3><p>U subotu je dostupna javna akcija u Domu omladine.</p><time>Danas · važi do 12. oktobra</time></span><span class="${state.notificationsRead?'':'unread-dot'}">›</span></button><button class="notification-item clickable" data-mobile-screen="appointments"><span class="notification-icon">✓</span><span><h3>Termin je potvrđen</h3><p>Subota u ${state.selectedTime}, Dom omladine.</p><time>Juče</time></span><span>›</span></button><button class="notification-item clickable" data-mobile-screen="education"><span class="notification-icon">i</span><span><h3>Kako da se pripremite</h3><p>Pročitajte odobrene savete pre dolaska.</p><time>5. oktobar</time></span><span>›</span></button>`,
  education:()=>`${mobileHeader('Vesti i edukacija','home',`<button class="icon-button" aria-label="Pretraga">${icon('search')}</button>`)}<div class="chips education-chips"><button class="chip active">Sve</button><button class="chip">Prvo davanje</button><button class="chip">Priprema</button><button class="chip">Afereza</button></div><article class="article-card"><span class="article-tag">Vodič</span><h3>Prvi put dajete krv?</h3><p>Šta poneti, koliko traje i šta se dešava u svakoj fazi.</p></article><article class="article-card"><span class="article-tag">Priprema</span><h3>Dan pre davanja</h3><p>Odobrene preporuke o odmoru, obroku i unosu tečnosti.</p></article><article class="article-card"><span class="article-tag">Vest Zavoda</span><h3>Izmena radnog vremena</h3><p>Ažurirano danas u 08:15 · zvanična informacija.</p></article><button class="secondary-button" data-mobile-screen="faq">Česta pitanja</button>`,
  faq:()=>`${mobileHeader('Pitanja i pomoć','education')}<div class="field"><input placeholder="Pretražite pitanja"></div><div class="faq-item"><button data-action="toggle-faq">Mogu li dati krv ako pijem lekove?<span>＋</span></button><div class="faq-answer hidden">Odgovor zavisi od leka i razloga terapije. Aplikacija ne donosi konačnu odluku; kontaktirajte Zavod ili pitajte lekara na prijemu.</div></div><div class="faq-item"><button data-action="toggle-faq">Koliko traje davanje?<span>＋</span></button><div class="faq-answer hidden">Samo davanje najčešće traje kraće od celog postupka. Planirajte vreme za prijem, upitnik, pregled i odmor.</div></div><div class="section-heading"><h3>Automatizovani pomoćnik</h3>${pill('Odobren sadržaj','info')}</div><div class="chat-bubble bot">Zdravo. Mogu da pronađem odobrene informacije, ali ne mogu da procenim da li možete dati krv.</div><div class="chat-bubble user">Gde mogu da dam krv u subotu?</div><div class="chat-bubble bot">Postoje dve javne akcije sa dostupnim terminima. Želite li da ih prikažem?</div><button class="secondary-button" data-action="contact-staff">Kontaktiraj Zavod</button>`,
  support:()=>`${mobileHeader('Podrška posle davanja','home')}<div class="warning-box">Ovaj kanal nije hitna služba i ne prati se neprekidno. Ako je potrebna hitna pomoć, postupite prema zvaničnom uputstvu.</div><article class="article-card"><span class="article-tag">Odobren savet</span><h3>Odmor i unos tečnosti</h3><p>Odmorite nakon davanja i pratite uputstvo koje ste dobili od zdravstvenog radnika.</p></article><div class="form-stack" style="margin-top:13px"><div class="field"><label>Kako možemo da pomognemo?</label><select><option>Pitanje posle davanja</option><option>Naknadno važna informacija o zdravlju</option><option>Primedba ili pohvala</option></select></div><div class="field"><label>Poruka</label><textarea></textarea></div><button class="primary-button full" data-action="send-support">Pošalji ovlašćenoj službi</button></div>`,
  privacy:()=>`${mobileHeader('Privatnost i komunikacija','profile')}<div class="info-box">Izbori su odvojeni i menjaju se u svakom trenutku. Osnovne funkcije rade i bez lokacije.</div><section class="settings-stack"><article class="setting-card"><div><strong>Pozivi na davanje</strong><small>Ciljani i teritorijalni pozivi kada su potrebni.</small></div><button class="switch on" data-action="toggle-setting" aria-pressed="true" aria-label="Pozivi na davanje uključeni"><span></span></button></article><article class="setting-card"><div><strong>Podsetnici za termin</strong><small>Dan ranije i nekoliko sati pre dolaska.</small></div><button class="switch on" data-action="toggle-setting" aria-pressed="true" aria-label="Podsetnici uključeni"><span></span></button></article><article class="setting-card"><div><strong>Trenutna lokacija</strong><small>Predlog akcija u blizini. Mapa kretanja se ne čuva.</small></div><button class="switch" data-action="toggle-setting" aria-pressed="false" aria-label="Trenutna lokacija isključena"><span></span></button></article><article class="setting-card"><div><strong>Vesti i edukacija</strong><small>Opšte, nehitne i stručno odobrene informacije.</small></div><button class="switch" data-action="toggle-setting" aria-pressed="false" aria-label="Vesti isključene"><span></span></button></article></section><button class="privacy-link" data-action="show-privacy-policy"><span>◉</span><span><strong>Politika privatnosti</strong><small>Kako čuvamo i koristimo podatke u aplikaciji</small></span><b>›</b></button><button class="primary-button full" style="margin-top:13px" data-action="save-settings">Sačuvaj podešavanja</button>`,
  pause:()=>`${mobileHeader('Pauziraj pozive','profile')}<div class="warning-box">Tokom pauze nećete dobijati pozive na davanje. Razlog nije obavezan i ne prikazuje se drugima.</div><div class="form-stack" style="margin-top:15px"><div class="field"><label>Pauziraj do</label><input type="date" value="2026-12-01"></div><div class="field"><label>Napomena za vas - opciono</label><textarea placeholder="Ovaj tekst nije potreban Zavodu."></textarea></div><button class="primary-button full" data-action="pause-invites">Potvrdi pauzu</button><button class="ghost-button" data-mobile-screen="profile">Odustani</button></div>`,
  questionnaire:()=>`${mobileHeader('Upitnik pre dolaska','profile')}<div class="warning-box"><strong>Buduća faza.</strong> Ekran se aktivira tek kada Zavod odobri obrazac i postupak. Digitalni unos ne zamenjuje pregled.</div><div class="section-heading"><h3>Nacrt upitnika</h3><span class="small-label">2 OD 6</span></div><div class="progress-track"><span style="width:33%"></span></div><article class="question-card"><h3>Da li se vaše zdravstveno stanje promenilo od poslednjeg davanja?</h3><div class="toggle-row"><button>Da</button><button class="active">Ne</button></div></article><article class="question-card"><h3>Da li trenutno uzimate lekove?</h3><div class="toggle-row"><button>Da</button><button>Ne</button></div></article><button class="primary-button full" data-action="save-questionnaire">Sačuvaj nacrt</button><p class="helper">Odgovori prethodnog davanja se ne preuzimaju kao aktuelni.</p>`
};

function portalHeader(kicker,title,actions=''){return `<header class="portal-header"><div><span class="eyebrow">${kicker}</span><h1>${title}</h1></div><div class="portal-actions">${actions}</div></header>`}
function metric(label,value,detail,delta=''){return `<article class="metric-card"><span>${label}</span><strong>${value}</strong><small class="${delta?'delta':''}">${detail}</small></article>`}
function panel(title,content,extra='',classes=''){return `<section class="panel ${classes}"><div class="panel-heading"><div><h2>${title}</h2>${extra}</div></div>${content}</section>`}

const adminIntakeRows=[
  ['Milica Petrović','MP','KZ-12OCT-4821','10:30','Zakazan','warning'],['Jelena Marković','JM','KZ-12OCT-4822','10:35','Zakazan','warning'],['Marko Ilić','MI','KZ-12OCT-4823','10:40','Zakazan','warning'],['Tamara Jovanović','TJ','KZ-12OCT-4824','10:45','Zakazan','warning'],['Nikola Pavlović','NP','KZ-12OCT-4825','10:50','Zakazan','warning'],['Ana Stojanović','AS','KZ-12OCT-4826','10:55','Zakazan','warning'],['Stefan Đorđević','SĐ','KZ-12OCT-4827','11:00','Zakazan','warning'],['Aleksandra Nikolić','AN','KZ-12OCT-4814','10:00','Prijavljen','info'],['Bojan Simić','BS','KZ-12OCT-4815','10:05','Prijavljen','info'],['Katarina Lazić','KL','KZ-12OCT-4816','10:10','Prijavljen','info'],['Nenad Milošević','NM','KZ-12OCT-4808','09:35','Kod tima','success'],['Marija Vuković','MV','KZ-12OCT-4809','09:40','Kod tima','success'],['Filip Ristić','FR','KZ-12OCT-4810','09:45','Kod tima','success']
];
const portalEvents=[
  {id:'dom-omladine',name:'Dom omladine',place:'Beograd',date:'19. sep · 10:00',access:'Javna',capacity:'34/40',percent:85,status:'U toku',tone:'success'},
  {id:'skc',name:'Studentski kulturni centar',place:'Novi Sad',date:'19. sep · 12:00',access:'Javna',capacity:'28/36',percent:78,status:'Objavljeno',tone:'info'},
  {id:'dunav',name:'Kompanija Dunav',place:'Zemun',date:'22. sep · 09:00',access:'Zaposleni',capacity:'18/30',percent:60,status:'Nacrt',tone:'neutral'}
];
function intakeCounts(){return {scheduled:adminIntakeRows.filter(row=>row[4]==='Zakazan').length,checkedIn:adminIntakeRows.filter(row=>row[4]==='Prijavljen').length,medical:adminIntakeRows.filter(row=>row[4]==='Kod tima').length,noShow:adminIntakeRows.filter(row=>row[4]==='Nije došao').length}}
function filteredIntakeRows(){const search=state.operationsQuery.trim().toLocaleLowerCase('sr');return adminIntakeRows.filter(row=>(state.operationsStatus==='all'||row[4]===state.operationsStatus)&&(!search||`${row[0]} ${row[2]} ${row[3]}`.toLocaleLowerCase('sr').includes(search)))}
function intakeRow([name,initials,code,time,status]){return `<tr tabindex="0" data-action="open-intake-record" data-reservation="${code}"><td><div class="person-cell"><span class="tiny-avatar">${initials}</span><div><strong>${name}</strong><br><small>${code}</small></div></div></td><td>${time}</td><td>${pill(status,statusTone(status))}</td><td><button class="table-button" data-action="open-intake-record" data-reservation="${code}">Detalj</button></td></tr>`}
function filteredEvents(){const search=state.eventQuery.trim().toLocaleLowerCase('sr');return portalEvents.filter(event=>(state.eventMunicipality==='all'||event.place===state.eventMunicipality)&&(state.eventStatus==='all'||event.status===state.eventStatus)&&(!search||`${event.name} ${event.place}`.toLocaleLowerCase('sr').includes(search)))}
function portalEventRow(event){return `<tr tabindex="0" data-action="edit-event" data-event="${event.id}"><td><strong>${event.name}</strong><br><small>${event.place}</small></td><td>${event.date}</td><td>${event.access}</td><td><div class="occupancy"><span>${event.capacity}</span><span class="bar"><span style="width:${event.percent}%"></span></span></div></td><td>${pill(event.status,event.tone)}</td><td><button class="table-button" data-action="edit-event" data-event="${event.id}">Otvori</button></td></tr>`}

const portalTemplates={
  dashboard:()=>{const counts=intakeCounts();return `${portalHeader('OPERATIVNI DEMO · DOM OMLADINE','Operativni pregled','<button class="primary-button compact" data-portal-screen="events">+ Nova akcija</button>')}<div class="metric-grid">${metric('Zakazano',counts.scheduled,'čekaju prijem')}${metric('Prijavljeni',counts.checkedIn,'u redu za medicinski tim')}${metric('Kod medicinskog tima',counts.medical,'logistički signal predat')}${metric('Nisu došli',counts.noShow,'evidentira prijem')}</div><div class="portal-grid">${panel('Današnja akcija',`<div class="action-row"><span class="status live"></span><div><strong>Dom omladine</strong><small>10:00–14:00 · Prijem 1 · 13 demonstracionih termina</small></div><button class="table-button" data-portal-screen="operations">Otvori tok</button></div><div class="info-box" style="margin-top:12px">Portal prati zbirni operativni status. Prijem radi u zasebnoj aplikaciji, a medicinski podaci nisu dostupni ovde.</div>`,'<p>Akcija, kapacitet i statusi bez zdravstvenih detalja</p>')}${panel('Sledeće radnje',`<div class="task-row"><span class="task-icon">↗</span><div><strong>Prati prijem i nedolaske</strong><small>Otvorite operativni tok sa tačnim statusima.</small></div><button class="table-button" data-portal-screen="operations">Otvori</button></div><div class="task-row"><span class="task-icon neutral">!</span><div><strong>Ispravke evidencije</strong><small>Zahtevi davalaca čekaju proveru.</small></div><button class="table-button" data-portal-screen="donors">Pregled</button></div><div class="task-row"><span class="task-icon neutral">3</span><div><strong>Tekstovi za stručnu proveru</strong><small>Sadržaj nije javno objavljen.</small></div><button class="table-button" data-portal-screen="content">Pregled</button></div>`,'<p>Svaka radnja ostaje u okviru odgovarajuće uloge</p>')}</div>`},
  events:()=>`${portalHeader('AKCIJE I TERMINI','Kalendar akcija','<button class="ghost-button" data-action="import-schedule">Uvezi raspored</button><button class="primary-button compact" data-action="create-event">+ Nova akcija</button>')}<div class="calendar-strip">${[['PON','14'],['UTO','15'],['SRE','16'],['ČET','17'],['PET','18'],['SUB','19'],['NED','20']].map(([day,date])=>`<button class="day-cell ${date===state.selectedPortalDay?'active':''}" data-action="select-portal-day" data-day="${date}"><span>${day}</span><strong>${date}</strong></button>`).join('')}</div>${panel('Akcije ove nedelje',`<div class="toolbar"><input class="search-input" data-portal-filter="events-query" value="${state.eventQuery}" placeholder="Pretraži naziv, mesto ili organizatora"><select class="select-control" data-portal-filter="events-municipality"><option value="all">Sve opštine</option><option value="Beograd" ${state.eventMunicipality==='Beograd'?'selected':''}>Beograd</option><option value="Novi Sad" ${state.eventMunicipality==='Novi Sad'?'selected':''}>Novi Sad</option><option value="Zemun" ${state.eventMunicipality==='Zemun'?'selected':''}>Zemun</option></select><select class="select-control" data-portal-filter="events-status"><option value="all">Svi statusi</option><option value="U toku" ${state.eventStatus==='U toku'?'selected':''}>U toku</option><option value="Objavljeno" ${state.eventStatus==='Objavljeno'?'selected':''}>Objavljeno</option><option value="Nacrt" ${state.eventStatus==='Nacrt'?'selected':''}>Nacrt</option></select></div><table class="data-table"><thead><tr><th>Akcija</th><th>Datum i vreme</th><th>Pristup</th><th>Popunjenost</th><th>Status</th><th></th></tr></thead><tbody>${filteredEvents().map(portalEventRow).join('')||'<tr><td colspan="6" class="empty-table">Nema akcija za izabrane filtere.</td></tr>'}</tbody></table>`,'<p>Pretraga i filteri rade nad demonstracionim skupom podataka</p>','table-panel')}`,
  checkin:()=>`${portalHeader('PRIJEM DAVALACA','Odvojeni radni prostor','<button class="primary-button compact" data-portal-screen="operations">Otvori tok prijema</button>')}<div class="portal-grid equal">${panel('Šta radi prijem',`<div class="task-row"><span class="task-icon">1</span><div><strong>Pronalazi tačnu rezervaciju</strong><small>QR kod ili broj rezervacije, pa provera identiteta uživo.</small></div></div><div class="task-row"><span class="task-icon">2</span><div><strong>Evidentira dolazak jednom</strong><small>Dupla prijava ne pravi novu posetu.</small></div></div><div class="task-row"><span class="task-icon">3</span><div><strong>Predaje samo logistički signal</strong><small>Medicinski tim otvara zaseban odobreni tok.</small></div></div>`,'<p>Prijem ne vidi zdravstvenu istoriju, krvnu grupu ni procenu podobnosti</p>')}${panel('Šta radi portal',`<div class="task-row"><span class="task-icon neutral">✓</span><div><strong>Prati zbirni operativni tok</strong><small>Zakazano, prijavljeno, kod medicinskog tima i nedolasci.</small></div></div><div class="task-row"><span class="task-icon neutral">↗</span><div><strong>Ne otvara karton davaoca</strong><small>Detalj rezervacije ostaje u ulozi prijema.</small></div></div><button class="primary-button full" style="margin-top:14px" data-portal-screen="operations">Otvori tok prijema</button>`,'<p>Administrator i koordinator vide samo minimum potreban za logistiku</p>')}</div>`,
  operations:()=>{const counts=intakeCounts(), rows=filteredIntakeRows();return `${portalHeader('DOM OMLADINE · PRIJEM 1','Tok prijema','<button class="ghost-button" data-action="refresh-operations">Osveži tok</button><button class="primary-button compact" data-portal-screen="checkin">Model uloga</button>')}<div class="metric-grid">${metric('Zakazano',counts.scheduled,'čeka prijem')}${metric('Prijavljeni',counts.checkedIn,'u redu za tim')}${metric('Kod medicinskog tima',counts.medical,'predati logistički')}${metric('Nisu došli',counts.noShow,'može označiti prijem')}</div>${panel('Današnji termini',`<div class="toolbar"><input class="search-input" data-portal-filter="operations-query" value="${state.operationsQuery}" placeholder="Pretraži ime ili broj rezervacije"><select class="select-control" data-portal-filter="operations-status"><option value="all">Svi operativni statusi</option><option value="Zakazan" ${state.operationsStatus==='Zakazan'?'selected':''}>Zakazano</option><option value="Prijavljen" ${state.operationsStatus==='Prijavljen'?'selected':''}>Prijavljeni</option><option value="Kod tima" ${state.operationsStatus==='Kod tima'?'selected':''}>Kod medicinskog tima</option><option value="Nije došao" ${state.operationsStatus==='Nije došao'?'selected':''}>Nisu došli</option></select><span class="result-count">${rows.length} od ${adminIntakeRows.length} termina</span></div><table class="data-table"><thead><tr><th>Davalac</th><th>Termin</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(intakeRow).join('')||'<tr><td colspan="4" class="empty-table">Nema termina koji odgovaraju izabranom filteru.</td></tr>'}</tbody></table><div class="info-box" style="margin-top:14px">Demonstracioni operativni prikaz: portal prati samo termin i status. Osnovni identitet je radni podatak sintetičke demonstracije; zdravstveni podaci nisu deo portala.</div>`,'<p>Pretraga, filter i detalj rade nad istim demonstracionim skupom</p>','table-panel')}`},
  campaigns:()=>`${portalHeader('CILJANI POZIVI','Kampanje i talasi','<button class="primary-button compact" data-portal-screen="campaign-builder">+ Nova kampanja</button>')}<div class="metric-grid">${metric('Aktivne','3','dve teritorijalne')}${metric('Čekaju odobrenje','1','publika spremna')}${metric('Rezervacije iz kampanja','68','ovog meseca',true)}${metric('Ograničenje učestalosti','7 dana','između sličnih poziva')}</div>${panel('Aktivne kampanje',`<table class="data-table"><thead><tr><th>Kampanja</th><th>Cilj</th><th>Talasi</th><th>Rezervacije</th><th>Status</th><th></th></tr></thead><tbody><tr><td><strong>Potreba za 0−</strong><br><small>Beograd · puna krv</small></td><td>20 dolazaka</td><td>2 od 3</td><td>16</td><td>${pill('Aktivna','success')}</td><td><button class="table-button" data-portal-screen="campaign-detail">Prati</button></td></tr><tr><td><strong>Akcija Novi Sad</strong><br><small>Južnobački okrug</small></td><td>35 dolazaka</td><td>1 od 2</td><td>22</td><td>${pill('Aktivna','success')}</td><td><button class="table-button">Prati</button></td></tr><tr><td><strong>Kompanija Dunav</strong><br><small>Samo zaposleni</small></td><td>25 dolazaka</td><td>nije pokrenuto</td><td>0</td><td>${pill('Čeka odobrenje','warning')}</td><td><button class="table-button" data-portal-screen="campaign-builder">Pregled</button></td></tr></tbody></table>`,'<p>Poslato, otvoreno, zakazano i realizovano ostaju odvojeni rezultati</p>','table-panel')}`,
  'campaign-builder':()=>`${portalHeader('NOVA KAMPANJA','Podešavanje publike','<button class="ghost-button" data-portal-screen="campaigns">Sačuvaj nacrt</button>')}<div class="builder-steps"><span class="active">1 Kriterijumi</span><span>2 Publika</span><span>3 Poruka</span><span>4 Odobrenje</span></div><div class="portal-grid">${panel('Kriterijumi kampanje',`<div class="form-grid"><div class="field"><label>Naziv</label><input value="Potreba za 0− · Beograd"></div><div class="field"><label>Vrsta davanja</label><select><option>Puna krv</option><option>Komponente</option></select></div><div class="field"><label>Krvna grupa</label><select><option>0−</option><option>0+</option><option>Sve grupe</option></select></div><div class="field"><label>Teritorija</label><select><option>Beograd</option><option>Novi Sad</option></select></div><div class="field"><label>Cilj potvrđenih dolazaka</label><input type="number" value="20"></div><div class="field"><label>Veličina prvog talasa</label><input type="number" value="50"></div></div><button class="primary-button compact" style="margin-top:15px" data-action="preview-audience">Ponovo izračunaj publiku</button>`,'<p>Medicinske kriterijume podešava samo ovlašćena uloga</p>')}${panel('Pregled publike',`<div class="audience-preview"><span class="small-label">ODGOVARA KRITERIJUMIMA</span><div class="audience-total">50 davalaca</div><p class="muted">Izračunato pre 2 minuta iz poslednje dostupne evidencije.</p><ul class="exclusion-list"><li><span>Vremenski razmak nije istekao</span><strong>18</strong></li><li><span>Aktivna pauza korisnika</span><strong>7</strong></li><li><span>Već pozvani sličnom kampanjom</span><strong>12</strong></li><li><span>Podatak nije dovoljno ažuran</span><strong>5</strong></li></ul></div><div class="warning-box" style="margin-top:12px">Publika se ponovo proverava neposredno pre svakog talasa.</div><button class="primary-button full" style="margin-top:12px" data-portal-screen="campaign-detail">Nastavi na pregled talasa</button>`,'<p>Razlozi isključenja bez otkrivanja zdravstvenih detalja</p>')}</div>`,
  'campaign-detail':()=>`${portalHeader('KAMPANJA · 0−','Praćenje talasa','<button class="danger-button" data-action="pause-campaign">Pauziraj kampanju</button>')}<div class="metric-grid">${metric('Cilj','20','potvrđenih dolazaka')}${metric('Zakazano','16','80% cilja')}${metric('Realizovano','9','potvrđeno')}${metric('Kapacitet','6','slobodnih termina')}</div>${panel('Talasi pozivanja',`<div class="wave-row"><span class="wave-label">Talas 1</span><span class="wave-progress"><span style="width:100%"></span></span><strong>50 poslato</strong><span>${pill('Završen','success')}</span></div><div class="wave-row"><span class="wave-label">Talas 2</span><span class="wave-progress"><span style="width:68%"></span></span><strong>34 poslato</strong><span>${pill('Aktivan','info')}</span></div><div class="wave-row"><span class="wave-label">Talas 3</span><span class="wave-progress"><span style="width:0%"></span></span><strong>0 poslato</strong><span>${pill('Čeka','neutral')}</span></div><div class="info-box" style="margin-top:14px">Sistem predlaže da se sačeka još 2 sata. Ovlašćeni zaposleni odlučuje da li se pokreće naredni talas.</div><div class="button-row portal-button-row"><button class="primary-button compact" data-action="launch-wave">Pokreni naredni talas</button><button class="ghost-button">Izmeni kriterijume</button></div>`,'<p>Automatsko zaustavljanje pri popunjenom cilju ili kapacitetu</p>')}`,
  donors:()=>`${portalHeader('DAVAOCI I PROVERE','Pretraga i zahtevi','<button class="ghost-button">Izvezi zbirni pregled</button>')}<div class="toolbar"><input class="search-input" placeholder="Ime, broj davaoca ili kontakt"><select class="select-control"><option>Svi zahtevi</option><option>Ispravke evidencije</option><option>Povezivanje naloga</option></select><button class="primary-button compact" data-action="search-donor">Pretraži</button></div><div class="portal-grid">${panel('Zahtevi koji čekaju',`<div class="task-row"><span class="task-icon">!</span><div><strong>Nedostaje davanje · Milica Petrović</strong><small>Prijavljeno 19. septembra · dokaz priložen</small></div><button class="table-button" data-action="review-correction">Otvori</button></div><div class="task-row"><span class="task-icon neutral">ID</span><div><strong>Povezivanje naloga · Nikola Jovanović</strong><small>Moguće podudaranje sa dva zapisa</small></div><button class="table-button">Otvori</button></div><div class="task-row"><span class="task-icon neutral">?</span><div><strong>Netačan datum · Ana Simić</strong><small>Prijavljeno juče</small></div><button class="table-button">Otvori</button></div>`,'<p>Pristup je ograničen ulogom zaposlenog</p>')}${panel('Pravila pristupa',`<div class="role-card"><h3>Koordinator akcija</h3><p>Vidi termine i logističke podatke, ali ne vidi zdravstvene odgovore.</p></div><div class="role-card" style="margin-top:9px"><h3>Medicinska služba</h3><p>Vidi zdravstveni upitnik i beleži ishod prema odobrenom postupku.</p></div><div class="role-card" style="margin-top:9px"><h3>PR i sadržaj</h3><p>Vidi samo zbirne rezultate i javne sadržaje.</p></div>`,'<p>Najmanji potreban obim podataka</p>')}</div>`,
  inventory:()=>`${portalHeader('ZALIHE KRVI','Stanje i javni prikaz','<button class="primary-button compact" data-action="save-inventory">Sačuvaj ažuriranje</button>')}<div class="info-box" style="margin-bottom:15px">Prikaz se odnosi na Institut za transfuziju i punu krv. Poslednje potvrđeno ažuriranje: danas u 08:30.</div><div class="blood-grid">${[['A+','Stabilno','18 dana',''],['A−','Niska zaliha','4 dana','low'],['B+','Stabilno','12 dana',''],['B−','Potrebno','3 dana','low'],['AB+','Stabilno','9 dana',''],['AB−','Kritično','1 dan','critical'],['0+','Niska zaliha','5 dana','low'],['0−','Kritično','1 dan','critical']].map(([group,status,level,cls])=>`<article class="blood-card ${cls}"><h3>${group}</h3><strong>${level}</strong><p>${status}</p><select class="select-control" style="width:100%"><option>${status}</option><option>Stabilno</option><option>Niska zaliha</option><option>Kritično</option></select></article>`).join('')}</div><div class="warning-box" style="margin-top:15px">Promena zaliha ne pokreće automatski masovne poruke. Kampanju otvara i odobrava odgovorna osoba.</div>`,
  content:()=>`${portalHeader('SADRŽAJ I PODRŠKA','Uređivanje i odobravanje','<button class="ghost-button">Sačuvaj nacrt</button><button class="primary-button compact" data-action="publish-content">Pošalji na odobrenje</button>')}<div class="editor-layout"><section class="editor-area"><span class="eyebrow">VODIČ ZA PRVO DAVANJE</span><h2>Kako da se pripremite za prvo davanje krvi</h2><p>Pre dolaska pojedite lagan obrok i pijte dovoljno tečnosti. Ponesite dokument sa fotografijom i odvojite vreme za prijem, razgovor i pregled.</p><p>Digitalna informacija ne zamenjuje razgovor sa zdravstvenim radnikom. Konačnu odluku o davanju donosi lekar prilikom svake posete.</p><div class="field"><label>Izvor i datum stručne provere</label><input value="Stručna služba Zavoda · provereno 18. septembra 2026."></div></section><aside><div class="revision-card"><strong>Status</strong><p>${pill('Stručna provera','warning')}</p></div><div class="revision-card"><strong>Verzija 4</strong><p class="muted">Jelena je izmenila uvod.</p><small>Danas u 10:14</small></div><div class="revision-card"><strong>Verzija 3</strong><p class="muted">Dr Marković je odobrio medicinski deo.</p><small>Juče u 16:48</small></div></aside></div>`,
  reports:()=>`${portalHeader('IZVEŠTAJI','Rezultati bez pogrešnih zaključaka','<button class="primary-button compact" data-action="export-report">Preuzmi izveštaj</button>')}<div class="metric-grid">${metric('Poslato','1.240','poruka')}${metric('Otvoreno','746','60% dostavljenih')}${metric('Zakazano','214','17% poslatih')}${metric('Realizovano','168','potvrđenih davanja')}</div><div class="portal-grid">${panel('Rezultat po mesecima',`<div class="chart">${[['APR',52],['MAJ',68],['JUN',83],['JUL',61],['AVG',74],['SEP',92]].map(([label,value])=>`<div class="chart-bar" style="height:${value}%"><strong>${value}</strong><span>${label}</span></div>`).join('')}</div>`,'<p>Potvrđena davanja povezana sa terminima i kampanjama</p>')}${panel('Napomena za tumačenje',`<div class="info-box">Poslata poruka, iskazana namera, rezervacija, dolazak i potvrđeno davanje nisu isti rezultat.</div><div class="task-row"><span class="task-icon neutral">1</span><div><strong>Novi davaoci</strong><small>34 potvrđena prva davanja</small></div></div><div class="task-row"><span class="task-icon neutral">2</span><div><strong>Ponovni dolasci</strong><small>61% u odabranom periodu</small></div></div>`,'<p>Metrike ostaju jasno razdvojene</p>')}</div>`,
  access:()=>`${portalHeader('UPRAVLJANJE PRISTUPOM','Uloge i trag promena','<button class="ghost-button" data-action="create-staff-invite">+ Dodaj korisnika</button>')}<div class="role-grid"><article class="role-card"><h3>Prijem</h3><p>Identitet, termin, dolazak i logistički status.</p></article><article class="role-card"><h3>Medicinska služba</h3><p>Upitnik, pregled i medicinski ishod posete.</p></article><article class="role-card"><h3>PR i sadržaj</h3><p>Javne objave, kampanje i zbirni rezultati.</p></article><article class="role-card"><h3>Koordinator</h3><p>Akcije, kapaciteti, termini i organizatori.</p></article><article class="role-card"><h3>Administrator</h3><p>Nalozi, konfiguracija i bezbednosni događaji.</p></article><article class="role-card"><h3>Revizor</h3><p>Čitanje traga promena bez izmene podataka.</p></article></div>${panel('Poslednje promene',`<div class="audit-row"><strong>Danas 10:42</strong><span>Jelena Marković</span><span>Promenila kapacitet akcije Dom omladine sa 36 na 40.</span><small>Akcija A-204</small></div><div class="audit-row"><strong>Danas 10:18</strong><span>Dr Ivan Marković</span><span>Odobrio stručni sadržaj vodiča za prvo davanje.</span><small>Aktivnost S-118</small></div><div class="audit-row"><strong>Danas 09:55</strong><span>Ana Ilić</span><span>Potvrdila administrativnu ispravku evidencije.</span><small>Zahtev I-482</small></div><div class="audit-row"><strong>Juče 16:30</strong><span>Sistem</span><span>Zaustavio naredni talas nakon popunjenog kapaciteta.</span><small>Kampanja K-77</small></div>`,'<p>Ko, kada i šta je promenio</p>','full-span')}`,
  integrations:()=>`${portalHeader('SISTEMSKA VEZA','API i integracije','<button class="ghost-button" data-action="check-api-health">Proveri vezu</button><button class="primary-button compact" data-action="check-api-operations">Proveri tok prijema</button>')}<div class="portal-grid equal">${panel('Status veze',`${apiStatusMarkup()}<div class="api-endpoint"><code>${configuredApiBase||'API_BASE nije podešen'}</code><small>Za lokalni prikaz dodajte <code>?api=http://127.0.0.1:3333</code> na admin URL.</small></div><div class="warning-box" style="margin-top:14px">Čak i kada demo API odgovori, on ne sadrži produkcionu prijavu, stvarne evidencije ni medicinske podatke.</div>`,'<p>Kontrolisana demonstraciona veza</p>')}${panel('Ugovorene rute',`<ul class="route-list"><li><code>GET /v1/portal/dashboard</code><span>Zbirni operativni pregled</span></li><li><code>GET /v1/portal/operations</code><span>Status termina bez zdravstvenih podataka</span></li><li><code>GET /v1/portal/events</code><span>Akcije i termini</span></li><li><code>GET /v1/portal/audit</code><span>Trag promena</span></li><li><code>POST /v1/staff/invitations</code><span>Demo pozivnica osoblju — bez slanja e-pošte</span></li></ul><button class="secondary-button" data-action="show-api-boundaries">Pogledaj granice pristupa</button>`,'<p>Produkcione rute čekaju odobrenje Zavoda</p>')}</div>${panel('Šta se aktivira kasnije',`<div class="integration-grid"><article><strong>Prijava zaposlenih</strong><span>SSO/MFA, dodela smene i opoziv uređaja</span></article><article><strong>Akcije i zalihe</strong><span>Samo potvrđen izvor, vlasništvo nad podacima i audit</span></article><article><strong>Medicinski tok</strong><span>Odvojen sistem i pravila Zavoda — nikad deo admin portala</span></article></div>`,'<p>Ove granice čuvamo i u prototipu</p>','full-span')}`
};

function renderPortal(screen=state.portalScreen){
  state.portalScreen=screen;
  $$('#portal-nav [data-portal-screen]').forEach(button=>button.classList.toggle('active',button.dataset.portalScreen===screen||(screen.startsWith('campaign-')&&button.dataset.portalScreen==='campaigns')));
  portalScreen.innerHTML=portalTemplates[screen]?.()||portalTemplates.dashboard();
  history.replaceState(null,'',`#portal/${screen}`);
}

function setMode(mode){
  state.mode=mode;
  $$('.switch-button').forEach(button=>button.classList.toggle('active',button.dataset.mode===mode));
  $('#mobile-view').classList.toggle('hidden',mode!=='mobile');
  $('#portal-view').classList.toggle('hidden',mode!=='portal');
  if(mode==='mobile')renderMobile(state.mobileScreen);else renderPortal(state.portalScreen);
}

function showDialog(title,content){$('#dialog-title').textContent=title;$('#dialog-content').innerHTML=content;dialog.showModal()}
function showDecisions(){showDialog('Odluke za pregled',`<div class="decision-grid"><article class="decision-card"><h3>1. Prijava i identitet</h3><p>Da li je lični broj davaoca dovoljan ili je potrebna dodatna institucionalna provera?</p></article><article class="decision-card"><h3>2. Okvirni datum</h3><p>Koja formulacija najjasnije odvaja vremenski razmak od medicinske podobnosti?</p></article><article class="decision-card"><h3>3. Mapa i lokacija</h3><p>Da li u MVP-u koristimo samo izabrane opštine ili i trenutnu lokaciju uz dozvolu?</p></article><article class="decision-card"><h3>4. Digitalna kartica</h3><p>Da li je kartica pomoćna identifikacija ili deo zvaničnog prijemnog postupka?</p></article><article class="decision-card"><h3>5. Kampanje</h3><p>Ko odobrava publiku, poruku, veličinu talasa i hitan izuzetak od mirnih sati?</p></article><article class="decision-card"><h3>6. Upitnik</h3><p>Da li ga prikazujemo u prvom pilotu ili tek posle formalnog odobrenja obrasca?</p></article><article class="decision-card"><h3>7. Javni prikaz zaliha</h3><p>Koji izvor, pragovi i učestalost ažuriranja mogu da garantuju tačnost?</p></article><article class="decision-card"><h3>8. Naziv i identitet</h3><p>Radni prototip još nema konačan naziv, logotip ni institucijski potpis.</p></article></div>`)}
function showScreenMap(){showDialog('Mapa mobilnih ekrana',`<div class="screen-map">${mobileCatalog.map(group=>`<section class="map-column"><h3>${group.title}</h3><ul>${group.items.map(item=>`<li>${item[1]}</li>`).join('')}</ul></section>`).join('')}</div>`)}

document.addEventListener('input',event=>{
  const filter=event.target.dataset.portalFilter;if(!filter)return;
  if(filter==='operations-query'){state.operationsQuery=event.target.value;renderPortal('operations')}
  if(filter==='events-query'){state.eventQuery=event.target.value;renderPortal('events')}
});
document.addEventListener('change',event=>{
  const filter=event.target.dataset.portalFilter;if(!filter)return;
  if(filter==='operations-status'){state.operationsStatus=event.target.value;renderPortal('operations')}
  if(filter==='events-municipality'){state.eventMunicipality=event.target.value;renderPortal('events')}
  if(filter==='events-status'){state.eventStatus=event.target.value;renderPortal('events')}
});

document.addEventListener('click',event=>{
  const mode=event.target.closest('[data-mode]');if(mode){setMode(mode.dataset.mode);return}
  const mobileTarget=event.target.closest('[data-mobile-screen]');if(mobileTarget){renderMobile(mobileTarget.dataset.mobileScreen);return}
  const portalTarget=event.target.closest('[data-portal-screen]');if(portalTarget){renderPortal(portalTarget.dataset.portalScreen);return}
  const time=event.target.closest('[data-time]');if(time&&!time.disabled){state.selectedTime=time.dataset.time;renderMobile('booking');return}
  const actionNode=event.target.closest('[data-action]');const action=actionNode?.dataset.action;if(!action)return;
  const actions={
    'show-decisions':showDecisions,'show-map':showScreenMap,'close-dialog':()=>dialog.close(),
    'resend-code':()=>showToast('Novi kod je poslat.'),'follow-event':()=>showToast('Pratićemo promene ove akcije.'),
    'confirm-booking':()=>renderMobile('booking-success'),'cancel-booking':()=>{showToast('Termin je otkazan i mesto je oslobođeno.');renderMobile('actions')},
    'refresh-qr':()=>showToast('Jednokratni QR kod je osvežen.'),'download-certificate':()=>showToast('Demo: potvrda bi bila bezbedno preuzeta.'),
    'send-correction':()=>{showToast('Zahtev je poslat na proveru.');renderMobile('history')},'share-achievement':()=>showToast('Demo vizual je pripremljen za pregled.'),
    'show-action-list':()=>{state.actionsView='list';renderMobile('actions')},'show-action-map':()=>{state.actionsView='map';renderMobile('actions')},
    'select-map':()=>{state.mapSelected=actionNode.dataset.point;renderMobile('actions')},'locate-map':()=>{streetMap?.fitBounds(Object.values(mapLocations).map(location=>location.coords),{padding:[28,28]});showToast('Prikazane su sve lokacije akcija.')},
    'mark-read':()=>{state.notificationsRead=true;showToast('Sva obaveštenja su označena kao pročitana.');renderMobile('notifications')},'contact-staff':()=>showToast('Otvoren je kontakt ovlašćene službe.'),
    'send-support':()=>showToast('Poruka je prosleđena ovlašćenoj službi.'),'save-settings':()=>showToast('Podešavanja su sačuvana.'),
    'toggle-setting':()=>{const enabled=actionNode.classList.toggle('on');actionNode.setAttribute('aria-pressed',String(enabled))},
    'show-privacy-policy':()=>showDialog('Politika privatnosti',`<div class="policy-copy"><p><strong>Vaši podaci služe samo za nalog, termine, potvrđenu evidenciju i izbore koje uključite.</strong></p><p>Lokacija je opciona i koristi se samo za predloge akcija u blizini. Aplikacija ne čuva mapu vašeg kretanja.</p><p>Zdravstveni detalji nisu deo obaveštenja, kampanja ni QR koda. Pristup evidenciji Zavoda ima samo ovlašćeno osoblje prema svojoj ulozi.</p><p>Možete promeniti komunikacione izbore u svakom trenutku i poslati zahtev za ispravku potvrđenih podataka.</p></div>`),
    'show-thanks':()=>showDialog('Zahvalnica',`<article class="thank-you-preview"><span>♥</span><h3>Hvala, Milice</h3><p>Vaših 5 potvrđenih davanja predstavljaju pet prilika za nekoga kome je pomoć potrebna.</p><small>Dobrovoljno davanje krvi · Od srca. Za život.</small></article>`),
    'pause-invites':()=>{showToast('Pozivi su pauzirani do izabranog datuma.');renderMobile('profile')},'save-questionnaire':()=>showToast('Nacrt je sačuvan lokalno u prototipu.'),
    'toggle-faq':()=>{const answer=event.target.closest('.faq-item').querySelector('.faq-answer');answer.classList.toggle('hidden')},
    'create-event':()=>showDialog('Nova akcija',`<div class="form-grid"><div class="field"><label>Naziv akcije</label><input placeholder="npr. Dom omladine"></div><div class="field"><label>Datum i vreme</label><input type="datetime-local"></div><div class="field"><label>Lokacija</label><input placeholder="Adresa i grad"></div><div class="field"><label>Kapacitet</label><input type="number" placeholder="40"></div></div><div class="warning-box" style="margin-top:14px">Demo obrazac ne objavljuje akciju. Produkcija zahteva odgovornu osobu, proveru kapaciteta i audit.</div><button class="primary-button compact" style="margin-top:14px" data-action="save-event-draft">Sačuvaj nacrt</button>`),
    'save-event-draft':()=>{dialog.close();showToast('Nacrt akcije je sačuvan samo u demonstracionom prikazu.')},
    'import-schedule':()=>showDialog('Uvoz rasporeda',`<div class="decision-card"><h3>Kontrolisan uvoz</h3><p>U produkciji se raspored uvozi samo iz odobrenog izvora Zavoda, uz proveru duplikata, kapaciteta i audit zapis.</p></div><button class="primary-button compact" style="margin-top:14px" data-action="confirm-demo-import">Prikaži demo uvoz</button>`),
    'confirm-demo-import':()=>{dialog.close();showToast('Demo raspored je spreman za pregled; ništa nije poslato niti objavljeno.')},
    'select-portal-day':()=>{state.selectedPortalDay=actionNode.dataset.day;renderPortal('events')},
    'edit-event':()=>{const item=portalEvents.find(entry=>entry.id===actionNode.dataset.event);if(!item)return;showDialog(`Akcija · ${item.name}`,`<div class="decision-grid"><article class="decision-card"><h3>${item.place}</h3><p>${item.date}<br>${item.access} pristup<br>Popunjenost: <strong>${item.capacity}</strong></p></article><article class="decision-card"><h3>Status objave</h3><p>${item.status}. Izmene su nacrt sve dok odgovorna osoba ne potvrdi objavu.</p></article></div><button class="primary-button compact" style="margin-top:14px" data-action="edit-event-draft">Uredi nacrt</button>`)} ,
    'edit-event-draft':()=>{dialog.close();showToast('Otvoren je radni nacrt akcije u demonstracionom režimu.')},
    'simulate-scan':()=>showToast('Identitet pronađen. Potrebna je provera dokumenta.'),'preview-audience':()=>showToast('Publika je ponovo izračunata iz demonstracionih podataka.'),
    'pause-campaign':()=>showToast('Kampanja je pauzirana. Novi pozivi se ne šalju.'),'launch-wave':()=>showToast('Naredni talas čeka potvrdu odgovorne osobe.'),
    'search-donor':()=>showToast('Pretraga koristi samo podatke dozvoljene ovoj ulozi.'),'review-correction':()=>showToast('Otvoren je trag zahteva i priloženih dokaza.'),
    'refresh-operations':()=>{showToast('Operativni tok je osvežen iz demonstracionog skupa.');renderPortal('operations')},
    'open-intake-record':()=>{const row=adminIntakeRows.find(item=>item[2]===actionNode.dataset.reservation);if(!row)return;showDialog('Operativni detalj rezervacije',`<div class="decision-grid"><article class="decision-card"><h3>${row[0]}</h3><p>Broj rezervacije: <strong>${row[2]}</strong><br>Termin: ${row[3]}<br>Operativni status: ${row[4]}</p></article><article class="decision-card"><h3>Granica pristupa</h3><p>Portal prati samo termin i logistički status. U realnom toku osnovni identitet vidi prijem; zdravstveni podaci nikad nisu dostupni ovom portalu.</p></article></div><div class="info-box" style="margin-top:14px">Vreme rezervacije, prijave i predaje pripada auditu ugovorenog API-ja. Nema stvarne evidencije Zavoda.</div>`);},
    'save-inventory':()=>showToast('Stanje je sačuvano sa vremenom i autorom izmene.'),'publish-content':()=>showToast('Sadržaj je poslat stručnoj službi na odobrenje.'),
    'export-report':()=>showDialog('Izvoz zbirnog izveštaja',`<div class="decision-card"><h3>Pre preuzimanja</h3><p>Izveštaj sadrži samo zbirne metrike. Lični i zdravstveni podaci se ne izvoze iz admin portala.</p></div><button class="primary-button compact" style="margin-top:14px" data-action="confirm-report-export">Pripremi demo izveštaj</button>`),
    'confirm-report-export':()=>{dialog.close();showToast('Demo zbirni izveštaj je pripremljen bez ličnih podataka.')},
    'create-staff-invite':()=>showDialog('Nova pozivnica osoblju',`<div class="form-grid"><div class="field"><label>Ime i prezime</label><input placeholder="Ime zaposlenog"></div><div class="field"><label>Službeni e-mail</label><input type="email" placeholder="ime@zavod.rs"></div><div class="field"><label>Uloga</label><select><option>Prijem</option><option>Koordinator</option><option>Medicinska služba</option></select></div><div class="field"><label>Dodeljena akcija</label><select><option>Dom omladine</option></select></div></div><div class="warning-box" style="margin-top:14px">Demo ne šalje e-poštu i ne aktivira nalog. Produkcija koristi službenu pozivnicu, MFA i dodelu akcije.</div><button class="primary-button compact" style="margin-top:14px" data-action="create-demo-invite">Kreiraj demo pozivnicu</button>`),
    'create-demo-invite':()=>{dialog.close();showToast('Demo pozivnica je evidentirana bez slanja e-pošte.')},
    'open-portal-profile':()=>showDialog('Prijavljeni korisnik',`<div class="decision-grid"><article class="decision-card"><h3>Jelena Marković</h3><p>Uloga: Koordinator akcija<br>Radni prostor: Dom omladine<br>Demonstraciona prijava</p></article><article class="decision-card"><h3>Granica pristupa</h3><p>Može upravljati akcijama i kapacitetima. Ne vidi zdravstvene odgovore ili medicinske ishode.</p></article></div><button class="ghost-button" style="margin-top:14px" data-action="close-dialog">Zatvori</button>`),
    'check-api-health':()=>checkConfiguredApi('/health'),'check-api-operations':()=>checkConfiguredApi('/v1/portal/operations'),
    'show-api-boundaries':()=>showDialog('Granice API pristupa',`<div class="decision-grid"><article class="decision-card"><h3>Portal</h3><p>Čita zbirni tok i operativni status, bez zdravstvenih informacija.</p></article><article class="decision-card"><h3>Prijem</h3><p>Radi samo u odvojenoj aplikaciji, sa tačnom rezervacijom i proverom identiteta.</p></article><article class="decision-card"><h3>Medicinski tim</h3><p>Odvojen tok i zasebna ovlašćenja. Nije ugrađen u admin portal.</p></article><article class="decision-card"><h3>Produkcija</h3><p>Zahteva Zavodov identitet, autentifikaciju, MFA, audit i odobrene izvore podataka.</p></article></div>`)
  };actions[action]?.();
});

dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});
renderMobileList();
const hash=location.hash.replace('#','').split('/');
if(hash[0]==='portal'||isAdminEntry){state.portalScreen=hash[1]||'dashboard';setMode('portal')}else{state.mobileScreen=hash[1]||'home';setMode('mobile')}
